fileVersion: 1
id: "22"
mappingDefinitions:
  BRONZE:
    database: MTANTRUM_DEV
    schema: TASTY_BYTES_SMALL
  GOLD:
    database: CLAUER_DEV
    schema: GOLD
  SAP-BRONZE:
    database: DOUG_DB
    schema: SAP_SOURCE
  SILVER:
    database: CLAUER_DEV
    schema: SILVER
name: Production
type: Environment
